### ISSUE TITLE
Player bouncing of stages

### ISSUE THREAD

**Issue by deadlykam** [deadlykam/JumpRace3D#1]
# Feature: Player bouncing of stages
#### Detail:
When the player lands on a stage make the player bounce off of it.
***
#### Tasks:
- [x] Make player bounce of stages.
- [x] Make bounce stage models.
- [x] Make a static bounce stage.
- [x] Make a static small bounce stage.
- [x] Make a slow moving bounce stage.
- [x] Make a high bounce stage. (This is the bottom one)
- [x] Make a breakable bounce stage.
- [x] Animate the stage.
***
