### ISSUE TITLE
Stage Detector Line

### ISSUE THREAD

**Issue by deadlykam** [deadlykam/JumpRace3D#15]
# Feature: Stage Detector Line
#### Details:
A line should generate beneath the player so that the user will know if they are above a stage or not. The line should change colour based on being under a stage or not.
***
#### Tasks:
- [x] The line will stretch to the bottom of the stage or the bouncy stages. Depends on which one it hits first.
- [x] When the line hits a stage turn the colour green.
- [x] When the line hits the ground/water turn the colour red.
