### ISSUE TITLE
Player Object

### ISSUE THREAD

**Issue by deadlykam** [deadlykam/JumpRace3D#2]
# Feature: Player Object
#### Details:
Make the player object. All the tasks for player object are below.
***
#### Tasks:
- [x] Make the basic character script.
- [x] Make the character animation script.
- [x] Make the player model.
***
