### ISSUE TITLE
Level Progression

### ISSUE THREAD

**Issue by deadlykam** [deadlykam/JumpRace3D#34]
# Feature: Level Progression
#### Details:
Once the player reaches the end of stage then there should be a prompt for starting next stage. So basically **Stage Reset** needs to be done.
***
#### Tasks:
- [x] When player reaches end stage then increment level.

- [x] When player reaches end stage reset all used stages.

- [x] When player reaches end stage start a new stage with new level.
