### ISSUE TITLE
Enemies

### ISSUE THREAD

**Issue by deadlykam** [deadlykam/JumpRace3D#39]
# Feature: Enemies
#### Details:
Give other enemy npcs that will race alongside the player. The enemies will follow the stage link to the end platform. Enemies will start ahead of the player.
***
#### Tasks:
- [x] The enemies will jump follow the stage link to the end platform.
- [x] Enemies will start ahead of the player, so will be in different stages.
- [x] Check if obstacle collision is needed for the enemy to kill it. **Edit: Not needed.**
