### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by deadlykam** [deadlykam/JumpRace3D#55]
# Feature: UI
#### Details:
Add all UI functionalities
***
#### Related Issues:
[Hide Enemies #54](#54 )
***
#### Tasks:
- [x] Show how far the player is from the end platform
- [x] Tap to start.
- [x] Tap to continue.
- [x] Tap to re-start after death.
- [x] Loading screen.
- [x] Show controls.
