### ISSUE TITLE
Character Animations

### ISSUE THREAD

**Issue by deadlykam** [deadlykam/JumpRace3D#59]
# Features: Character Animations
#### Details:
Create Jump and Fall animations for the character.
***
#### Tasks:
- [x] **Idle 1:** Hand and feet flapping.
- [x] **Idle 2:** Parkour Type (Knee to chest).

- [x] **Jump 1:** Front flip jump.
- [x] **Jump 2:** Back flip jump.

- [x] **Land 1:** Landing animation.
***
