### ISSUE TITLE
Visual Effects

### ISSUE THREAD

**Issue by deadlykam** [deadlykam/JumpRace3D#73]
# Feature: Visual Effects
#### Details:
Give all the visul effects needed in the game.
***
#### Tasks:
- [x] When characters jumps off of a bouncy stage give a visual effect.
- [x] When player jumps off of booster give a visual effect.
- [x] When player finishes the game give a visual effect.
- [x] When player falls into the water give a visual effect.
