### ISSUE TITLE
Update: Audio

### ISSUE THREAD

**Issue by deadlykam** [deadlykam/JumpRace3D#84]
# Update: Audio
#### Details:
Add music and game sound effects.
***
#### Tasks:
- [x] Music.
- [x] Stage Bounce sfx.
- [x] Splash sfx.
- [x] Character dying sfx.
- [x] Confetti sfx.
- [x] Booster pick sfx.
- [x] Winner sfx.
